### ISSUE TITLE
lua_sandbox and TLS support

### ISSUE THREAD

**Issue by bbinet** [tacigar/lua-mqtta#4]
I'm looking for a lua mqtt library to be used in a lua sandbox in [Hindsight](https://github.com/mozilla-services/hindsight), so I have few questions about your lua-mqtta project.

Do you think it could be compatible with the [lua_sandbox](https://github.com/mozilla-services/lua_sandbox) without too much work? Note that I think the lua_sandbox is based on Lua5.1.
I could create a dedicated mqtt extension in [lua_sandbox_extensions](https://github.com/mozilla-services/lua_sandbox_extensions).

Also does lua-mqtta client support TLS?

And would you consider lua-mqtta as production ready yet?

Thanks.

**Comment by tacigar** [comment]
Hi, bbinet.

> And would you consider lua-mqtta as production ready yet?

Yes.

I needed an asynchronous MQTT library written in Lua for my research, but I did not find it, so I made this library.
So, this has only the minimum functionality required for my research(so does not support TLS), and now I do not maintain it.
So you should not use this library :(

**Comment by bbinet** [comment]
OK, thanks for the info.

On Saturday, November 25, 2017, tacigar <notifications@github.com> wrote:
> Hi, bbinet.
>
> And would you consider lua-mqtta as production ready yet?
>
> Yes.
>
> I needed an asynchronous MQTT library written in Lua for my research, but
I did not find it, so I made this library.
> So, this has only the minimum functionality required for my research(so
does not support TLS), and now I do not maintain it.
> So you should not use this library :(
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/e8I39T6UEf_ARu-_UyjfkeSjDG5CbDZJo2rtDORqNmMGAQLMdqtC5YRVAccQBpCmHodb7dxXJ-J0XdyKuk1DBzr2GoOfwMILv5um1HzCHlvG8fxDIGGBAKEBYOKJUzjKG9y-7coje5xCIOtV7JbI4OJfsrb3Wg=s0-d-e1-ft#https://github.com/notifications/beacon/AAEp-ThEmaMBFlOfKAXYxPdHWlSD3JrVks5s51IBgaJpZM4Qp5tc.gif>
